### ISSUE TITLE
Widget not following the required option

### ISSUE THREAD

**Issue by oswaldoacauan** [hennessyevan/netlify-cms-widget-youtube#1]
## Expected Behavior
When using `required: false` the Youtube field should not be required.

## Actual Behavior
The Youtube widget does not follow the `required` field.

## Steps to Reproduce the Problem

  1. Create a youtube field with `required: false`
  1. Try to publish without filling the youtube field
  1. CMS will not publish and will show a invalid style on the youtube field

**Comment by oswaldoacauan** [comment]
any ideia on how to achieve fix this? @hennessyevan

**Comment by hennessyevan** [comment]
@oswaldoacauan I think I do, I may not be able to get around to it for a few days though but the widget validates entries as being proper youtube links and marks it valid/invalid in netlify-cms. I suspect that bypassing that validation when the required field is specified may do the trick 👍 

If you wanted to mess around with that, PR's are totally welcome. Otherwise I should be able to get to it soon enough.

I'm thinking of starting with short-circuiting https://github.com/hennessyevan/netlify-cms-widget-youtube/blob/master/src/Control.js#L156 with the required field

**Comment by jlev** [comment]
This seems like it is is still a problem. I can add a check to `this.props.field.get("required")` in componentDidUpdate, but might also want to change the default state to valid, so that empty fields can be saved.
